# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-07-04 12:43
from __future__ import unicode_literals

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PeptideStructureData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('sequence', models.CharField(max_length=1000)),
                ('file', models.FileField(default='media/NULL/default.txt', storage=django.core.files.storage.FileSystemStorage(location='E:\\StartInnovating\\Projects\\7_ALLERGEN_WebService\\djangoApp\\allergenProject'), upload_to='media/upload/')),
                ('status', models.CharField(max_length=20)),
            ],
        ),
    ]
