# Generated by Django 2.0.8 on 2019-01-04 17:37

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peptidestructuredata',
            name='file',
            field=models.FileField(default='NULL', storage=django.core.files.storage.FileSystemStorage(location='/home/robomex/Desktop/MLTool_demo/allergenProject'), upload_to='media/modelData/upload/'),
        ),
    ]
